variable "region" {}
variable "name" {}
variable "environment" {}
variable "container_port" {}
variable "image" {}
variable "task_cpu" {}
variable "task_memory" {}
variable "vpc_id" {}
variable "public_subnets" {}
variable "private_subnets" {}
variable "alb_sg" {}
variable "ecs_sg" {}
